# logging configs
log:
  dir: /tmp/recipe
logging.file: ${log.dir}/recipe.log
logging:
  file:
    max-size: 100MB
    max-history: 30
  level:
    guru.springframework: DEBUG
#    org.guru.springframework.*: ERROR
#    org.hibernate.*: ERROR
#    guru.guru.springframework: DEBUG